<#import "parts/common.ftlh" as c>

<@c.page>
    <a href="/filling">Добавление путевого листа</a><br><br>
    <a href="/addingRoutes">Добавление маршрутов</a><br><br>
    <a href="/waybillEditing">Редактирование путевого листа</a><br><br>
    <a href="/viewRouteSheetByDate">Просмотр путевого листа по дате</a><br><br>
    <a href="/formExcel">Сформировать Excel</a><br><br>
    <a href="/deleteDataBase">Очистить Базу Данных</a><br><br>
    ${errorMessage}
</@c.page>