<#import "parts/common.ftlh" as c>

<@c.page>
    <a href="/information">Просмотр статистики</a><br><br>
    <a href="/filling">Заполнение путевого листа</a><br><br>
    <a href="/date">Добавление маршрутов</a><br><br>
    <a href="/date2">Просмотр путевого листа по дате</a><br><br>
    <a href="">Редактирование путевого листа</a><br><br>
    <a href="/date3">Вывод на печать</a><br><br>
</@c.page>